// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	ACLRule          *aCLRule
	ClientConnection *clientConnection
	ReceivedMessage  *receivedMessage
	Role             *role
	Topic            *topic
	User             *user
	UserRole         *userRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ACLRule = &Q.ACLRule
	ClientConnection = &Q.ClientConnection
	ReceivedMessage = &Q.ReceivedMessage
	Role = &Q.Role
	Topic = &Q.Topic
	User = &Q.User
	UserRole = &Q.UserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		ACLRule:          newACLRule(db, opts...),
		ClientConnection: newClientConnection(db, opts...),
		ReceivedMessage:  newReceivedMessage(db, opts...),
		Role:             newRole(db, opts...),
		Topic:            newTopic(db, opts...),
		User:             newUser(db, opts...),
		UserRole:         newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ACLRule          aCLRule
	ClientConnection clientConnection
	ReceivedMessage  receivedMessage
	Role             role
	Topic            topic
	User             user
	UserRole         userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		ACLRule:          q.ACLRule.clone(db),
		ClientConnection: q.ClientConnection.clone(db),
		ReceivedMessage:  q.ReceivedMessage.clone(db),
		Role:             q.Role.clone(db),
		Topic:            q.Topic.clone(db),
		User:             q.User.clone(db),
		UserRole:         q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		ACLRule:          q.ACLRule.replaceDB(db),
		ClientConnection: q.ClientConnection.replaceDB(db),
		ReceivedMessage:  q.ReceivedMessage.replaceDB(db),
		Role:             q.Role.replaceDB(db),
		Topic:            q.Topic.replaceDB(db),
		User:             q.User.replaceDB(db),
		UserRole:         q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	ACLRule          IACLRuleDo
	ClientConnection IClientConnectionDo
	ReceivedMessage  IReceivedMessageDo
	Role             IRoleDo
	Topic            ITopicDo
	User             IUserDo
	UserRole         IUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ACLRule:          q.ACLRule.WithContext(ctx),
		ClientConnection: q.ClientConnection.WithContext(ctx),
		ReceivedMessage:  q.ReceivedMessage.WithContext(ctx),
		Role:             q.Role.WithContext(ctx),
		Topic:            q.Topic.WithContext(ctx),
		User:             q.User.WithContext(ctx),
		UserRole:         q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
