// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mkrab/internal/data/model"
)

func newACLRule(db *gorm.DB, opts ...gen.DOOption) aCLRule {
	_aCLRule := aCLRule{}

	_aCLRule.aCLRuleDo.UseDB(db, opts...)
	_aCLRule.aCLRuleDo.UseModel(&model.ACLRule{})

	tableName := _aCLRule.aCLRuleDo.TableName()
	_aCLRule.ALL = field.NewAsterisk(tableName)
	_aCLRule.ID = field.NewUint64(tableName, "id")
	_aCLRule.CreatedAt = field.NewTime(tableName, "created_at")
	_aCLRule.UpdatedAt = field.NewTime(tableName, "updated_at")
	_aCLRule.DeletedAt = field.NewField(tableName, "deleted_at")
	_aCLRule.RoleID = field.NewUint64(tableName, "role_id")
	_aCLRule.Operation = field.NewString(tableName, "operation")
	_aCLRule.Effect = field.NewString(tableName, "effect")
	_aCLRule.TopicFilter = field.NewString(tableName, "topic_filter")

	_aCLRule.fillFieldMap()

	return _aCLRule
}

type aCLRule struct {
	aCLRuleDo aCLRuleDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	RoleID      field.Uint64
	Operation   field.String
	Effect      field.String
	TopicFilter field.String

	fieldMap map[string]field.Expr
}

func (a aCLRule) Table(newTableName string) *aCLRule {
	a.aCLRuleDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aCLRule) As(alias string) *aCLRule {
	a.aCLRuleDo.DO = *(a.aCLRuleDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aCLRule) updateTableName(table string) *aCLRule {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.RoleID = field.NewUint64(table, "role_id")
	a.Operation = field.NewString(table, "operation")
	a.Effect = field.NewString(table, "effect")
	a.TopicFilter = field.NewString(table, "topic_filter")

	a.fillFieldMap()

	return a
}

func (a *aCLRule) WithContext(ctx context.Context) IACLRuleDo { return a.aCLRuleDo.WithContext(ctx) }

func (a aCLRule) TableName() string { return a.aCLRuleDo.TableName() }

func (a aCLRule) Alias() string { return a.aCLRuleDo.Alias() }

func (a aCLRule) Columns(cols ...field.Expr) gen.Columns { return a.aCLRuleDo.Columns(cols...) }

func (a *aCLRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aCLRule) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["role_id"] = a.RoleID
	a.fieldMap["operation"] = a.Operation
	a.fieldMap["effect"] = a.Effect
	a.fieldMap["topic_filter"] = a.TopicFilter
}

func (a aCLRule) clone(db *gorm.DB) aCLRule {
	a.aCLRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aCLRule) replaceDB(db *gorm.DB) aCLRule {
	a.aCLRuleDo.ReplaceDB(db)
	return a
}

type aCLRuleDo struct{ gen.DO }

type IACLRuleDo interface {
	gen.SubQuery
	Debug() IACLRuleDo
	WithContext(ctx context.Context) IACLRuleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IACLRuleDo
	WriteDB() IACLRuleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IACLRuleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IACLRuleDo
	Not(conds ...gen.Condition) IACLRuleDo
	Or(conds ...gen.Condition) IACLRuleDo
	Select(conds ...field.Expr) IACLRuleDo
	Where(conds ...gen.Condition) IACLRuleDo
	Order(conds ...field.Expr) IACLRuleDo
	Distinct(cols ...field.Expr) IACLRuleDo
	Omit(cols ...field.Expr) IACLRuleDo
	Join(table schema.Tabler, on ...field.Expr) IACLRuleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IACLRuleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IACLRuleDo
	Group(cols ...field.Expr) IACLRuleDo
	Having(conds ...gen.Condition) IACLRuleDo
	Limit(limit int) IACLRuleDo
	Offset(offset int) IACLRuleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IACLRuleDo
	Unscoped() IACLRuleDo
	Create(values ...*model.ACLRule) error
	CreateInBatches(values []*model.ACLRule, batchSize int) error
	Save(values ...*model.ACLRule) error
	First() (*model.ACLRule, error)
	Take() (*model.ACLRule, error)
	Last() (*model.ACLRule, error)
	Find() ([]*model.ACLRule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ACLRule, err error)
	FindInBatches(result *[]*model.ACLRule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ACLRule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IACLRuleDo
	Assign(attrs ...field.AssignExpr) IACLRuleDo
	Joins(fields ...field.RelationField) IACLRuleDo
	Preload(fields ...field.RelationField) IACLRuleDo
	FirstOrInit() (*model.ACLRule, error)
	FirstOrCreate() (*model.ACLRule, error)
	FindByPage(offset int, limit int) (result []*model.ACLRule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IACLRuleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aCLRuleDo) Debug() IACLRuleDo {
	return a.withDO(a.DO.Debug())
}

func (a aCLRuleDo) WithContext(ctx context.Context) IACLRuleDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aCLRuleDo) ReadDB() IACLRuleDo {
	return a.Clauses(dbresolver.Read)
}

func (a aCLRuleDo) WriteDB() IACLRuleDo {
	return a.Clauses(dbresolver.Write)
}

func (a aCLRuleDo) Session(config *gorm.Session) IACLRuleDo {
	return a.withDO(a.DO.Session(config))
}

func (a aCLRuleDo) Clauses(conds ...clause.Expression) IACLRuleDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aCLRuleDo) Returning(value interface{}, columns ...string) IACLRuleDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aCLRuleDo) Not(conds ...gen.Condition) IACLRuleDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aCLRuleDo) Or(conds ...gen.Condition) IACLRuleDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aCLRuleDo) Select(conds ...field.Expr) IACLRuleDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aCLRuleDo) Where(conds ...gen.Condition) IACLRuleDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aCLRuleDo) Order(conds ...field.Expr) IACLRuleDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aCLRuleDo) Distinct(cols ...field.Expr) IACLRuleDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aCLRuleDo) Omit(cols ...field.Expr) IACLRuleDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aCLRuleDo) Join(table schema.Tabler, on ...field.Expr) IACLRuleDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aCLRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IACLRuleDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aCLRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) IACLRuleDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aCLRuleDo) Group(cols ...field.Expr) IACLRuleDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aCLRuleDo) Having(conds ...gen.Condition) IACLRuleDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aCLRuleDo) Limit(limit int) IACLRuleDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aCLRuleDo) Offset(offset int) IACLRuleDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aCLRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IACLRuleDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aCLRuleDo) Unscoped() IACLRuleDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aCLRuleDo) Create(values ...*model.ACLRule) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aCLRuleDo) CreateInBatches(values []*model.ACLRule, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aCLRuleDo) Save(values ...*model.ACLRule) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aCLRuleDo) First() (*model.ACLRule, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ACLRule), nil
	}
}

func (a aCLRuleDo) Take() (*model.ACLRule, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ACLRule), nil
	}
}

func (a aCLRuleDo) Last() (*model.ACLRule, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ACLRule), nil
	}
}

func (a aCLRuleDo) Find() ([]*model.ACLRule, error) {
	result, err := a.DO.Find()
	return result.([]*model.ACLRule), err
}

func (a aCLRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ACLRule, err error) {
	buf := make([]*model.ACLRule, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aCLRuleDo) FindInBatches(result *[]*model.ACLRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aCLRuleDo) Attrs(attrs ...field.AssignExpr) IACLRuleDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aCLRuleDo) Assign(attrs ...field.AssignExpr) IACLRuleDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aCLRuleDo) Joins(fields ...field.RelationField) IACLRuleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aCLRuleDo) Preload(fields ...field.RelationField) IACLRuleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aCLRuleDo) FirstOrInit() (*model.ACLRule, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ACLRule), nil
	}
}

func (a aCLRuleDo) FirstOrCreate() (*model.ACLRule, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ACLRule), nil
	}
}

func (a aCLRuleDo) FindByPage(offset int, limit int) (result []*model.ACLRule, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aCLRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aCLRuleDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aCLRuleDo) Delete(models ...*model.ACLRule) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aCLRuleDo) withDO(do gen.Dao) *aCLRuleDo {
	a.DO = *do.(*gen.DO)
	return a
}
