// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mkrab/internal/data/model"
)

func newClientConnection(db *gorm.DB, opts ...gen.DOOption) clientConnection {
	_clientConnection := clientConnection{}

	_clientConnection.clientConnectionDo.UseDB(db, opts...)
	_clientConnection.clientConnectionDo.UseModel(&model.ClientConnection{})

	tableName := _clientConnection.clientConnectionDo.TableName()
	_clientConnection.ALL = field.NewAsterisk(tableName)
	_clientConnection.ID = field.NewUint64(tableName, "id")
	_clientConnection.CreatedAt = field.NewTime(tableName, "created_at")
	_clientConnection.UpdatedAt = field.NewTime(tableName, "updated_at")
	_clientConnection.DeletedAt = field.NewField(tableName, "deleted_at")
	_clientConnection.ClientID = field.NewString(tableName, "client_id")
	_clientConnection.Status = field.NewString(tableName, "status")
	_clientConnection.Username = field.NewString(tableName, "username")
	_clientConnection.RemoteAddress = field.NewString(tableName, "remote_address")
	_clientConnection.Listener = field.NewString(tableName, "listener")
	_clientConnection.ProtocolVersion = field.NewUint8(tableName, "protocol_version")
	_clientConnection.CleanSession = field.NewBool(tableName, "clean_session")
	_clientConnection.ConnectedAt = field.NewTime(tableName, "connected_at")
	_clientConnection.DisconnectedAt = field.NewTime(tableName, "disconnected_at")
	_clientConnection.LastDisconnectedIP = field.NewString(tableName, "last_disconnected_ip")
	_clientConnection.DisconnectReason = field.NewString(tableName, "disconnect_reason")
	_clientConnection.SessionExpired = field.NewBool(tableName, "session_expired")

	_clientConnection.fillFieldMap()

	return _clientConnection
}

type clientConnection struct {
	clientConnectionDo clientConnectionDo

	ALL                field.Asterisk
	ID                 field.Uint64
	CreatedAt          field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field
	ClientID           field.String
	Status             field.String
	Username           field.String
	RemoteAddress      field.String
	Listener           field.String
	ProtocolVersion    field.Uint8
	CleanSession       field.Bool
	ConnectedAt        field.Time
	DisconnectedAt     field.Time
	LastDisconnectedIP field.String
	DisconnectReason   field.String
	SessionExpired     field.Bool

	fieldMap map[string]field.Expr
}

func (c clientConnection) Table(newTableName string) *clientConnection {
	c.clientConnectionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c clientConnection) As(alias string) *clientConnection {
	c.clientConnectionDo.DO = *(c.clientConnectionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *clientConnection) updateTableName(table string) *clientConnection {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.ClientID = field.NewString(table, "client_id")
	c.Status = field.NewString(table, "status")
	c.Username = field.NewString(table, "username")
	c.RemoteAddress = field.NewString(table, "remote_address")
	c.Listener = field.NewString(table, "listener")
	c.ProtocolVersion = field.NewUint8(table, "protocol_version")
	c.CleanSession = field.NewBool(table, "clean_session")
	c.ConnectedAt = field.NewTime(table, "connected_at")
	c.DisconnectedAt = field.NewTime(table, "disconnected_at")
	c.LastDisconnectedIP = field.NewString(table, "last_disconnected_ip")
	c.DisconnectReason = field.NewString(table, "disconnect_reason")
	c.SessionExpired = field.NewBool(table, "session_expired")

	c.fillFieldMap()

	return c
}

func (c *clientConnection) WithContext(ctx context.Context) IClientConnectionDo {
	return c.clientConnectionDo.WithContext(ctx)
}

func (c clientConnection) TableName() string { return c.clientConnectionDo.TableName() }

func (c clientConnection) Alias() string { return c.clientConnectionDo.Alias() }

func (c clientConnection) Columns(cols ...field.Expr) gen.Columns {
	return c.clientConnectionDo.Columns(cols...)
}

func (c *clientConnection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *clientConnection) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 16)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["client_id"] = c.ClientID
	c.fieldMap["status"] = c.Status
	c.fieldMap["username"] = c.Username
	c.fieldMap["remote_address"] = c.RemoteAddress
	c.fieldMap["listener"] = c.Listener
	c.fieldMap["protocol_version"] = c.ProtocolVersion
	c.fieldMap["clean_session"] = c.CleanSession
	c.fieldMap["connected_at"] = c.ConnectedAt
	c.fieldMap["disconnected_at"] = c.DisconnectedAt
	c.fieldMap["last_disconnected_ip"] = c.LastDisconnectedIP
	c.fieldMap["disconnect_reason"] = c.DisconnectReason
	c.fieldMap["session_expired"] = c.SessionExpired
}

func (c clientConnection) clone(db *gorm.DB) clientConnection {
	c.clientConnectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c clientConnection) replaceDB(db *gorm.DB) clientConnection {
	c.clientConnectionDo.ReplaceDB(db)
	return c
}

type clientConnectionDo struct{ gen.DO }

type IClientConnectionDo interface {
	gen.SubQuery
	Debug() IClientConnectionDo
	WithContext(ctx context.Context) IClientConnectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IClientConnectionDo
	WriteDB() IClientConnectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IClientConnectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IClientConnectionDo
	Not(conds ...gen.Condition) IClientConnectionDo
	Or(conds ...gen.Condition) IClientConnectionDo
	Select(conds ...field.Expr) IClientConnectionDo
	Where(conds ...gen.Condition) IClientConnectionDo
	Order(conds ...field.Expr) IClientConnectionDo
	Distinct(cols ...field.Expr) IClientConnectionDo
	Omit(cols ...field.Expr) IClientConnectionDo
	Join(table schema.Tabler, on ...field.Expr) IClientConnectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IClientConnectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IClientConnectionDo
	Group(cols ...field.Expr) IClientConnectionDo
	Having(conds ...gen.Condition) IClientConnectionDo
	Limit(limit int) IClientConnectionDo
	Offset(offset int) IClientConnectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IClientConnectionDo
	Unscoped() IClientConnectionDo
	Create(values ...*model.ClientConnection) error
	CreateInBatches(values []*model.ClientConnection, batchSize int) error
	Save(values ...*model.ClientConnection) error
	First() (*model.ClientConnection, error)
	Take() (*model.ClientConnection, error)
	Last() (*model.ClientConnection, error)
	Find() ([]*model.ClientConnection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ClientConnection, err error)
	FindInBatches(result *[]*model.ClientConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ClientConnection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IClientConnectionDo
	Assign(attrs ...field.AssignExpr) IClientConnectionDo
	Joins(fields ...field.RelationField) IClientConnectionDo
	Preload(fields ...field.RelationField) IClientConnectionDo
	FirstOrInit() (*model.ClientConnection, error)
	FirstOrCreate() (*model.ClientConnection, error)
	FindByPage(offset int, limit int) (result []*model.ClientConnection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IClientConnectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c clientConnectionDo) Debug() IClientConnectionDo {
	return c.withDO(c.DO.Debug())
}

func (c clientConnectionDo) WithContext(ctx context.Context) IClientConnectionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c clientConnectionDo) ReadDB() IClientConnectionDo {
	return c.Clauses(dbresolver.Read)
}

func (c clientConnectionDo) WriteDB() IClientConnectionDo {
	return c.Clauses(dbresolver.Write)
}

func (c clientConnectionDo) Session(config *gorm.Session) IClientConnectionDo {
	return c.withDO(c.DO.Session(config))
}

func (c clientConnectionDo) Clauses(conds ...clause.Expression) IClientConnectionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c clientConnectionDo) Returning(value interface{}, columns ...string) IClientConnectionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c clientConnectionDo) Not(conds ...gen.Condition) IClientConnectionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c clientConnectionDo) Or(conds ...gen.Condition) IClientConnectionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c clientConnectionDo) Select(conds ...field.Expr) IClientConnectionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c clientConnectionDo) Where(conds ...gen.Condition) IClientConnectionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c clientConnectionDo) Order(conds ...field.Expr) IClientConnectionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c clientConnectionDo) Distinct(cols ...field.Expr) IClientConnectionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c clientConnectionDo) Omit(cols ...field.Expr) IClientConnectionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c clientConnectionDo) Join(table schema.Tabler, on ...field.Expr) IClientConnectionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c clientConnectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IClientConnectionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c clientConnectionDo) RightJoin(table schema.Tabler, on ...field.Expr) IClientConnectionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c clientConnectionDo) Group(cols ...field.Expr) IClientConnectionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c clientConnectionDo) Having(conds ...gen.Condition) IClientConnectionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c clientConnectionDo) Limit(limit int) IClientConnectionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c clientConnectionDo) Offset(offset int) IClientConnectionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c clientConnectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IClientConnectionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c clientConnectionDo) Unscoped() IClientConnectionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c clientConnectionDo) Create(values ...*model.ClientConnection) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c clientConnectionDo) CreateInBatches(values []*model.ClientConnection, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c clientConnectionDo) Save(values ...*model.ClientConnection) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c clientConnectionDo) First() (*model.ClientConnection, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClientConnection), nil
	}
}

func (c clientConnectionDo) Take() (*model.ClientConnection, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClientConnection), nil
	}
}

func (c clientConnectionDo) Last() (*model.ClientConnection, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClientConnection), nil
	}
}

func (c clientConnectionDo) Find() ([]*model.ClientConnection, error) {
	result, err := c.DO.Find()
	return result.([]*model.ClientConnection), err
}

func (c clientConnectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ClientConnection, err error) {
	buf := make([]*model.ClientConnection, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c clientConnectionDo) FindInBatches(result *[]*model.ClientConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c clientConnectionDo) Attrs(attrs ...field.AssignExpr) IClientConnectionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c clientConnectionDo) Assign(attrs ...field.AssignExpr) IClientConnectionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c clientConnectionDo) Joins(fields ...field.RelationField) IClientConnectionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c clientConnectionDo) Preload(fields ...field.RelationField) IClientConnectionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c clientConnectionDo) FirstOrInit() (*model.ClientConnection, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClientConnection), nil
	}
}

func (c clientConnectionDo) FirstOrCreate() (*model.ClientConnection, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClientConnection), nil
	}
}

func (c clientConnectionDo) FindByPage(offset int, limit int) (result []*model.ClientConnection, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c clientConnectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c clientConnectionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c clientConnectionDo) Delete(models ...*model.ClientConnection) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *clientConnectionDo) withDO(do gen.Dao) *clientConnectionDo {
	c.DO = *do.(*gen.DO)
	return c
}
