// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"mkrab/internal/data/model"
)

func newReceivedMessage(db *gorm.DB, opts ...gen.DOOption) receivedMessage {
	_receivedMessage := receivedMessage{}

	_receivedMessage.receivedMessageDo.UseDB(db, opts...)
	_receivedMessage.receivedMessageDo.UseModel(&model.ReceivedMessage{})

	tableName := _receivedMessage.receivedMessageDo.TableName()
	_receivedMessage.ALL = field.NewAsterisk(tableName)
	_receivedMessage.ID = field.NewUint64(tableName, "id")
	_receivedMessage.CreatedAt = field.NewTime(tableName, "created_at")
	_receivedMessage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_receivedMessage.DeletedAt = field.NewField(tableName, "deleted_at")
	_receivedMessage.ReceivedAt = field.NewTime(tableName, "received_at")
	_receivedMessage.ClientID = field.NewString(tableName, "client_id")
	_receivedMessage.Username = field.NewString(tableName, "username")
	_receivedMessage.Topic = field.NewString(tableName, "topic")
	_receivedMessage.Payload = field.NewString(tableName, "payload")
	_receivedMessage.QoS = field.NewUint8(tableName, "qo_s")
	_receivedMessage.Retained = field.NewBool(tableName, "retained")
	_receivedMessage.Duplicate = field.NewBool(tableName, "duplicate")

	_receivedMessage.fillFieldMap()

	return _receivedMessage
}

type receivedMessage struct {
	receivedMessageDo receivedMessageDo

	ALL        field.Asterisk
	ID         field.Uint64
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	ReceivedAt field.Time
	ClientID   field.String
	Username   field.String
	Topic      field.String
	Payload    field.String
	QoS        field.Uint8
	Retained   field.Bool
	Duplicate  field.Bool

	fieldMap map[string]field.Expr
}

func (r receivedMessage) Table(newTableName string) *receivedMessage {
	r.receivedMessageDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r receivedMessage) As(alias string) *receivedMessage {
	r.receivedMessageDo.DO = *(r.receivedMessageDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *receivedMessage) updateTableName(table string) *receivedMessage {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint64(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.ReceivedAt = field.NewTime(table, "received_at")
	r.ClientID = field.NewString(table, "client_id")
	r.Username = field.NewString(table, "username")
	r.Topic = field.NewString(table, "topic")
	r.Payload = field.NewString(table, "payload")
	r.QoS = field.NewUint8(table, "qo_s")
	r.Retained = field.NewBool(table, "retained")
	r.Duplicate = field.NewBool(table, "duplicate")

	r.fillFieldMap()

	return r
}

func (r *receivedMessage) WithContext(ctx context.Context) IReceivedMessageDo {
	return r.receivedMessageDo.WithContext(ctx)
}

func (r receivedMessage) TableName() string { return r.receivedMessageDo.TableName() }

func (r receivedMessage) Alias() string { return r.receivedMessageDo.Alias() }

func (r receivedMessage) Columns(cols ...field.Expr) gen.Columns {
	return r.receivedMessageDo.Columns(cols...)
}

func (r *receivedMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *receivedMessage) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["received_at"] = r.ReceivedAt
	r.fieldMap["client_id"] = r.ClientID
	r.fieldMap["username"] = r.Username
	r.fieldMap["topic"] = r.Topic
	r.fieldMap["payload"] = r.Payload
	r.fieldMap["qo_s"] = r.QoS
	r.fieldMap["retained"] = r.Retained
	r.fieldMap["duplicate"] = r.Duplicate
}

func (r receivedMessage) clone(db *gorm.DB) receivedMessage {
	r.receivedMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r receivedMessage) replaceDB(db *gorm.DB) receivedMessage {
	r.receivedMessageDo.ReplaceDB(db)
	return r
}

type receivedMessageDo struct{ gen.DO }

type IReceivedMessageDo interface {
	gen.SubQuery
	Debug() IReceivedMessageDo
	WithContext(ctx context.Context) IReceivedMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReceivedMessageDo
	WriteDB() IReceivedMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReceivedMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReceivedMessageDo
	Not(conds ...gen.Condition) IReceivedMessageDo
	Or(conds ...gen.Condition) IReceivedMessageDo
	Select(conds ...field.Expr) IReceivedMessageDo
	Where(conds ...gen.Condition) IReceivedMessageDo
	Order(conds ...field.Expr) IReceivedMessageDo
	Distinct(cols ...field.Expr) IReceivedMessageDo
	Omit(cols ...field.Expr) IReceivedMessageDo
	Join(table schema.Tabler, on ...field.Expr) IReceivedMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReceivedMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReceivedMessageDo
	Group(cols ...field.Expr) IReceivedMessageDo
	Having(conds ...gen.Condition) IReceivedMessageDo
	Limit(limit int) IReceivedMessageDo
	Offset(offset int) IReceivedMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReceivedMessageDo
	Unscoped() IReceivedMessageDo
	Create(values ...*model.ReceivedMessage) error
	CreateInBatches(values []*model.ReceivedMessage, batchSize int) error
	Save(values ...*model.ReceivedMessage) error
	First() (*model.ReceivedMessage, error)
	Take() (*model.ReceivedMessage, error)
	Last() (*model.ReceivedMessage, error)
	Find() ([]*model.ReceivedMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReceivedMessage, err error)
	FindInBatches(result *[]*model.ReceivedMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ReceivedMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReceivedMessageDo
	Assign(attrs ...field.AssignExpr) IReceivedMessageDo
	Joins(fields ...field.RelationField) IReceivedMessageDo
	Preload(fields ...field.RelationField) IReceivedMessageDo
	FirstOrInit() (*model.ReceivedMessage, error)
	FirstOrCreate() (*model.ReceivedMessage, error)
	FindByPage(offset int, limit int) (result []*model.ReceivedMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReceivedMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r receivedMessageDo) Debug() IReceivedMessageDo {
	return r.withDO(r.DO.Debug())
}

func (r receivedMessageDo) WithContext(ctx context.Context) IReceivedMessageDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r receivedMessageDo) ReadDB() IReceivedMessageDo {
	return r.Clauses(dbresolver.Read)
}

func (r receivedMessageDo) WriteDB() IReceivedMessageDo {
	return r.Clauses(dbresolver.Write)
}

func (r receivedMessageDo) Session(config *gorm.Session) IReceivedMessageDo {
	return r.withDO(r.DO.Session(config))
}

func (r receivedMessageDo) Clauses(conds ...clause.Expression) IReceivedMessageDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r receivedMessageDo) Returning(value interface{}, columns ...string) IReceivedMessageDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r receivedMessageDo) Not(conds ...gen.Condition) IReceivedMessageDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r receivedMessageDo) Or(conds ...gen.Condition) IReceivedMessageDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r receivedMessageDo) Select(conds ...field.Expr) IReceivedMessageDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r receivedMessageDo) Where(conds ...gen.Condition) IReceivedMessageDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r receivedMessageDo) Order(conds ...field.Expr) IReceivedMessageDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r receivedMessageDo) Distinct(cols ...field.Expr) IReceivedMessageDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r receivedMessageDo) Omit(cols ...field.Expr) IReceivedMessageDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r receivedMessageDo) Join(table schema.Tabler, on ...field.Expr) IReceivedMessageDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r receivedMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReceivedMessageDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r receivedMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IReceivedMessageDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r receivedMessageDo) Group(cols ...field.Expr) IReceivedMessageDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r receivedMessageDo) Having(conds ...gen.Condition) IReceivedMessageDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r receivedMessageDo) Limit(limit int) IReceivedMessageDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r receivedMessageDo) Offset(offset int) IReceivedMessageDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r receivedMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReceivedMessageDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r receivedMessageDo) Unscoped() IReceivedMessageDo {
	return r.withDO(r.DO.Unscoped())
}

func (r receivedMessageDo) Create(values ...*model.ReceivedMessage) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r receivedMessageDo) CreateInBatches(values []*model.ReceivedMessage, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r receivedMessageDo) Save(values ...*model.ReceivedMessage) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r receivedMessageDo) First() (*model.ReceivedMessage, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceivedMessage), nil
	}
}

func (r receivedMessageDo) Take() (*model.ReceivedMessage, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceivedMessage), nil
	}
}

func (r receivedMessageDo) Last() (*model.ReceivedMessage, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceivedMessage), nil
	}
}

func (r receivedMessageDo) Find() ([]*model.ReceivedMessage, error) {
	result, err := r.DO.Find()
	return result.([]*model.ReceivedMessage), err
}

func (r receivedMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReceivedMessage, err error) {
	buf := make([]*model.ReceivedMessage, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r receivedMessageDo) FindInBatches(result *[]*model.ReceivedMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r receivedMessageDo) Attrs(attrs ...field.AssignExpr) IReceivedMessageDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r receivedMessageDo) Assign(attrs ...field.AssignExpr) IReceivedMessageDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r receivedMessageDo) Joins(fields ...field.RelationField) IReceivedMessageDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r receivedMessageDo) Preload(fields ...field.RelationField) IReceivedMessageDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r receivedMessageDo) FirstOrInit() (*model.ReceivedMessage, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceivedMessage), nil
	}
}

func (r receivedMessageDo) FirstOrCreate() (*model.ReceivedMessage, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceivedMessage), nil
	}
}

func (r receivedMessageDo) FindByPage(offset int, limit int) (result []*model.ReceivedMessage, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r receivedMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r receivedMessageDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r receivedMessageDo) Delete(models ...*model.ReceivedMessage) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *receivedMessageDo) withDO(do gen.Dao) *receivedMessageDo {
	r.DO = *do.(*gen.DO)
	return r
}
