// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"mkrab/internal/broker"
	"mkrab/internal/config"
	"mkrab/internal/data"
	"mkrab/internal/data/repo"
)

// Injectors from wire.go:

func Initialize(configPath string) (*Application, func(), error) {
	configConfig, err := config.Load(configPath)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := data.OpenFromConfig(configConfig)
	if err != nil {
		return nil, nil, err
	}
	query := data.NewQuery(db)
	repositories := repo.New(query)
	database := data.NewDatabase(db, repositories)
	listenerSet, err := broker.NewListeners(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := repositories.Users
	authACLHook := broker.NewAuthACLHook(userRepository)
	connectionRepository := repositories.Connections
	clientConnectionHook := broker.NewClientConnectionHook(connectionRepository)
	messageRepository := repositories.Messages
	topicRepository := repositories.Topics
	messageStore := broker.NewMessageStore(configConfig, messageRepository, topicRepository)
	server, err := broker.NewServer(configConfig, listenerSet, authACLHook, clientConnectionHook, messageStore)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	application := New(configConfig, database, server)
	return application, func() {
		cleanup()
	}, nil
}
